---

- name: Setup Eclipse Adoptium yum repository
  ansible.builtin.template:
    src: "adoptium.repo.j2"
    dest: "/etc/yum.repos.d/adoptium.repo"
    owner: "root"
    group: "root"
    mode: "0644"

- name: Set this jdk as the default alternative
  community.general.alternatives:
    name: "java"
    path: "/usr/lib/jvm/temurin-{{ temurin_jdk_version }}-jdk/bin/java"
  when: temurin_set_default
